project:
  type: website

website:
  title: "ElektronikEinfach"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - Spannung-und-Strom.qmd
          - Bauteile.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



